### ISSUE TITLE
Can you make one for ruby ?

### ISSUE THREAD

**Issue by thiagovsk** [rodrigosiqueira/lappis_vimrc#1]
Will be awesome

**Comment by thiagovsk** [comment]
like:
https://github.com/intridea/ruby-style-guide

**Comment by chocoelho** [comment]
Have you tried using ftplugin? There you can apply your syntax specific configuration. You can create this folder under your .vim directory($HOME/.vim/ftplugin), and there you create a ruby.vim or another language with vim extension to apply specific configuration, like tab configuration since it changes from language to language.

**Comment by thiagovsk** [comment]
You can make this? I'm very newbie.

Explain step by step =D
@carloshfoliveira

**Comment by chocoelho** [comment]
All syntax specific changes you need can be set at a ruby.vim file located at $HOME/.vim/ftplugin/ruby.vim. Don't worry if this file/folder doesn't exist. mkdir -p the folder and touch the file :]

**Comment by rodrigosiqueira** [comment]
Dude... now it is time to revive this subject :)
I'm working to mix our vim with seocam's vim :)

**Comment by rodrigosiqueira** [comment]
@thiagovsk How about help me to improve ruby.vim? :)

https://github.com/rodrigosiqueira/lappis_vimrc/blob/ruby_vim/ftplugin/ruby.vim

**Comment by rodrigosiqueira** [comment]
@thiagovsk I mixed our .vimrc with @seocam 's .vimrc, and added support for ruby. How about tried it?
